### ISSUE TITLE
Question: What "community"?

### ISSUE THREAD

**Issue by b-g** [dematerializer/unicode-emoji-annotations#2]
Many thanks for this II! 👍 

The readme and the tagline of the repo is referring to  a "community" e.g. "with extensions provided by the community". It is not clear to (me) what you mean with "community" and who provided those extensions. Could you elaborate on this (and clarify in the readme)?

**Comment by dematerializer** [comment]
As this is an open source project, by "community" I mean the open source community on GitHub in general and in particular the community that will hopefully build around this project in the future. I provided an initial set of supplemental community annotations - authored by myself originally out of pure necessity - that should serve as a baseline for further discussions and development.

I would expand the first paragraph of the readme like so:

> This project aims to preserve CLDR emoji annotation data with respect to the original source as closely as possible while offering supplemental annotation data authored by a community that will hopefully build around this project in the future. An initial set of community annotations created by the original project maintainer serves as a baseline for further discussions and development.

As for the tagline and throughout the readme I would like to continue using the short term "the community".

What do you think? Would this clear things up?

**Comment by b-g** [comment]
Great! Very clear now. You could also stress this e.g. "PRs of supplemental annotation are welcome!"

BTW I did not want to be picky ... I just was confused whether there is some secret emoji community which I not aware of etc.

**Comment by dematerializer** [comment]
Please find the new clarification in new version 1.0.3: https://www.npmjs.com/package/unicode-emoji-annotations#community-annotations
